{
 "title": "Apache Spark Application Metrics",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "spark_app",
    "label": "Application",
    "query": "label_values({role=\"driver\"},app_name)"
   },
   {
    "name": "app_instance",
    "label": "Instance",
    "query": "label_values({role=\"driver\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\".+executor_threadpool_activeTasks\", role=\"executor\", instance=\"$app_instance\"})",
     "legendFormat": "Total active tasks"
    },
    {
     "expr": "sum({__name__=~\".+executor_threadpool_completeTasks\", role=\"executor\", instance=\"$app_instance\"})",
     "legendFormat": "Total complete tasks"
    }
   ]
  },
  {
   "title": "Complete Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+executor_threadpool_completeTasks\", role=\"executor\", instance=\"$app_instance\"}",
     "legendFormat": "{{role}} {{number}}"
    }
   ]
  },
  {
   "title": "Task Execution Time per Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+executor_runTime\", role=\"executor\", instance=\"$app_instance\"}",
     "legendFormat": "{{role}} {{number}} runtime"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+executor_threadpool_activeTasks\", role=\"executor\", instance=\"$app_instance\"}",
     "legendFormat": "{{role}} {{number}}"
    }
   ]
  },
  {
   "title": "CPU Time per Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".+executor_cpuTime\", role=\"executor\", instance=\"$app_instance\"}",
     "legendFormat": "{{role}} {{number}}"
    }
   ]
  }
 ]
}